inherits = "material_darker"

"ui.background" = {}

"ui.help" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.popup" = { bg = "black" }
"ui.cursor.match" = { fg = "accent", modifiers = ["underlined"] }
"ui.menu" = { bg = "black" }
"ui.menu.selected" = { modifiers = ["reversed"] }


